### ISSUE TITLE
Battery and Switch Locations?

### ISSUE THREAD

**Issue by ErichKinder** [dnlbauer/splitkeyboard#2]
Any chance you could post a picture or diagram for which side the switch and which points the battery are soldered to? It's not super clear from the PCB alone.

**Comment by dnlbauer** [comment]
The switch should be soldered on the opposite side (the bottom side) of the pcb. For the battery, they should be soldered to the uppermost pins on the board which are marked as + and -. I store the battery sandwhiched between the MCU and the board, but you could also solder it on the bottom side and hide it under the keyboard i guess. Just make sure you get the polarity right. I heard of cases where the red wire was not on the +.

Here are some pictures that show how I placed things.

Let me know if this helps!
![PXL_20230822_082010894](https://github.com/dnlbauer/corax56-keyboard/assets/4690162/5744de1b-6e86-4a2a-8ba9-bf32c3d798b6)
![PXL_20230822_081922137](https://github.com/dnlbauer/corax56-keyboard/assets/4690162/9bbd1cae-f577-4a7f-b732-73ec3832ef36)
![PXL_20230822_081930956](https://github.com/dnlbauer/corax56-keyboard/assets/4690162/d6a00893-2cd6-4cca-b5e6-8def299a4a79)
![PXL_20230822_081646803](https://github.com/dnlbauer/corax56-keyboard/assets/4690162/ba4f75a3-e0a6-485e-aa5d-83c406dafde2)

**Comment by dnlbauer** [comment]
Heres anotherone.

![image](https://github.com/dnlbauer/corax56-keyboard/assets/4690162/54d3b121-aa4b-477f-9eb5-3e9ee2c7a3e7)

**Comment by ErichKinder** [comment]
That's perfect, thanks! Super excited to build this!
