### ISSUE TITLE
Version with less thumb keys?

### ISSUE THREAD

**Issue by zawnk** [dnlbauer/splitkeyboard#3]
First, thanks for creating this keyboard an open-sourcing it :) I'm strongly considering building it, but I have a brief question: is there any realistic chance for an alternative version with only two instead of four thumb keys (dropping the left two)? (I also wouldn't need the single key at the outer edge but that's out of the way)

I assume chances to be not that high, but figured that asking before ordering the PCBs wouldn't hurt :)

**Comment by dnlbauer** [comment]
Hi,

I'm ~planning~ not planning to make a version with less thumbnails right now. PRs are welcome though if you want to give it a shot yourself! :) 

I thought about making a version without the outer key for some time since I'm rarely using it. However when and if this will happen, I can't say. So I suggest not not wait for this to happen.

**Comment by zawnk** [comment]
> I'm planning to make a version with less thumbnails right now. PRs are welcome though if you want to give it a shot yourself! :)

I wish, sadly I know near to nothing about KiCad/designing the PCB and even less about adjusting the case model :D

> So I suggest not not wait for this to happen.

Does this apply to both the less thumb keys _and_ the single key? I'm not particularly in a rush, I still need to order diodes and 1-2 other small things from China :)

**Comment by dnlbauer** [comment]
> I wish, sadly I know near to nothing about KiCad/designing the PCB

This was me before starting the project. 😉

> Does this apply to both the less thumb keys and the single key?

Both. I'm not planning to work on less thumb keys and for removing the outer button: I'm playing with the thought to do this but don't know when I find enough time to tackle this. Likely not this year.

**Comment by zawnk** [comment]
I've now ordered the pieces for the 54 key version, that's good enough for me, I'll just ignore the extra thumb keys (or just not solder any switches on it) :) So if you think it's unlikely that you create even more versions, feel free to close this issue. 

PS: I've started looking into ergogen thanks to you and referred your ergogen files a few times already at reddit when people had questions/needed examples! Life has kept me too busy to look deeply into it, but I will in the future :)
