### ISSUE TITLE
Unable to get reset switch, battery on/off switch and encoder up/down working

### ISSUE THREAD

**Issue by soumilgurjar** [dnlbauer/splitkeyboard#4]
Thanks for making this fantastic keyboard! It's one of the few low-profile split keyboards with a number row out there with an aggressive stagger.

I have recently built two sets of this keyboard and I have run into the following issues on both of them:
- The reset switch does not work on either half. I am unable to put the nice!nano v2 into bootloader mode using it, and have to resort to directly shorting the appropriate pins twice to do so.
- The battery connected to the PCB does not work, i.e the battery on/off switch does not power the micro-controller. Therefore I have needed to directly connect the battery to the MCU.
- The encoder works but only on the key press, the up/down scroll of the encoder does not perform any action.

Could you perhaps help me diagnose the issues? Since the same issues have occured on both keyboard builds and the components work on other keyboards that I have built, I am wondering if there is possibly an issue with the PCB related to these aspects. Any input would be appreciated. Thanks!

Unrelated: What does the instruction on the PCB - 'Solder jumpers on back' - mean?

**Comment by soumilgurjar** [comment]
I was able to figure it out soon after opening this issue. But I'll leave this here for future reference and close the issue. The solution to all those above issues is to solder the jumpers on the back side of each half. Putting a tiny blob of solder on each of the jumpers marked in red resolves all the issues.

If someone is using the nice!view, they would need to solder the corresponding jumpers as well.

![pcb_render_back_solder_jumpers](https://github.com/dnlbauer/corax56-keyboard/assets/95701317/d3b2b7e9-7ffe-4664-989a-52691e9f7d07)

**Comment by dnlbauer** [comment]
Great to hear there is another Corax out there :) And even better to hear that you already figured it out. 

These things are probably kinda hard to figure out unless you already built  a board that requires to solder jumpers. There are another 5 jumpers that are not marked in your picture where the nice nano connects (you only need them if you want to use a display).

For things like this, it would be really nice to have a good build guide. Mine is fully assembled but if someone ever starts a new build of a corax, it would be great to have some high detail step-by-step pictures to use for a tutorial! Read: Contributors welcome :)

**Comment by zawnk** [comment]
> There are another 5 jumpers that are not marked in your picture where the nice nano connects (you only need them if you want to use a display).

Is there any harm in soldering the jumpers if you don't plan to use an OLED for now? (they're not available currently). It would be nice if I wouldn't have to disassemble everything and solder the OLED jumpers later when the OLED arrives.

Also, if you don't use OLEDs (at first), i guess you have to compile ZMK with the OLED lines commented out?

**Comment by dnlbauer** [comment]
Theres no harm if you solder them. You also don't have to disable oled in ZMK. ZMK doesnt care if there is a display connected or not and most of the battery power displaying requires will be the consumption of the display and not from the MCU calculating the display signal.

My suggestion is to solder the jumpers and leave the firmware as is unless you want to play with the firmware anyways.
